services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      MONGODB_URI: mongodb://root:example@db:27017
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./data:/data/db
